BASE = ../../../..

TARGETS = stm32f4
PROGS = test_sdram
test_sdram_SOURCES = test_sdram.stm32f4.cc

MODULES = ucoo/hal/gpio ucoo/hal/sdram ucoo/utils ucoo/base/test ucoo/hal/usb

include $(BASE)/build/top.mk
