BASE = ../../..

TARGETS = host stm32f4
PROGS = test_fifo
stm32f4_PROGS = test_delay
test_fifo_SOURCES = test_fifo.cc
test_delay_SOURCES = test_delay.cc

MODULES = utils base/test hal/usb

include $(BASE)/build/top.mk
