BASE = ../../../..

TARGETS = stm32f4
PROGS = test_avrisp
test_avrisp_SOURCES = test_avrisp.cc

MODULES = ucoo/dev/avrisp ucoo/hal/spi ucoo/hal/gpio ucoo/base/test \
	  ucoo/hal/usb ucoo/utils

include $(BASE)/build/top.mk
